Fix a few problems with local user removal in ssh connector
1. Instead of exiting on the first error, attempt the rest of the
   operations and collect the error to be returned at the end. This
   ensures that one user in the wrong state doesn't block the creation
   and delete of all other users

2. Ignore exit status 1 from pkill. The user being removed may not be
   running any processes, so pkill may exit with status 1 and that's ok.
   In the future we can look to implement this logic in Go, which might
   give us more granular information about why the operation failed.

3. Kill all processes before removing any users. This may give the
   processes time to exit before we try to remove the user. Removing the
   user will fail if they still have processes running. Also use SIGKILL
   instead of SIGTERM, which should also speed up process exit.

diff --git a/internal/connector/testdata/bin/userdel b/internal/connector/testdata/bin/userdel
--- a/internal/connector/testdata/bin/userdel
+++ b/internal/connector/testdata/bin/userdel
@@ -1,3 +1,6 @@
 #!/usr/bin/env sh
 set -eu
 (echo -n "userdel "; printf "'%s' " "$@"; echo) >> ${TEST_CONNECTOR_USER_LOG_FILE}
+
+# simulate failing to remove a user
+if [ "$2" = "failremove" ]; then exit 8; fi
